### ISSUE TITLE
Private implementation using homogeneous coordinates

### ISSUE THREAD

**Issue by mpizenberg** [opensolid/geometry#16]
Have you already considered taking advantage of [homogeneous coordinates](https://en.wikipedia.org/wiki/Homogeneous_coordinates) for your private data types?

**Comment by ianmackenzie** [comment]
Well, right now OpenSolid doesn't actually have any private or opaque data types, so no =) I went back and forth but I think in most cases having exposed constructors for basic stuff like `Point3d` and `Triangle3d` is the right approach - it makes it obvious what's going on, the data types are simple enough that they shouldn't need much changing, and it's quite convenient. The kicker is that the core types have some circular dependencies (e.g. `Point3d.rotateAround` takes an `Axis3d` argument, but an `Axis3d` has a `Point3d` origin point) and since in Elm there's no such thing as 'package private' the only way to make that work is to have a set of shared public exposed types that all modules can work with.

It's possible that some future internal code could use homogeneous coordinates for stuff like projection calculations - I'm certainly aware of them - but I don't see an immediate application so I'm going to close this issue for now.

**Comment by mpizenberg** [comment]
Right, complexifying before having the real need of it is not a good idea. Just wished to know your point of view since it would ease for example intersection computations and of course some projective transformations.

As for the private/public debate. Maybe a files organization like this coud help:
```elm
-- Private/Types.elm
module Private.Types exposing (Point2d(Point2d))
type Point2d = Point2d (Float, Float)
```
```elm
-- Public/Types.elm
module Public.Types exposing (Point2d)
import Private.Types exposing (Point2d)
```
```elm
-- Point2d.elm
module Point2d.elm exposing (fromCoordinates)
import Private.Types exposing (..)
fromCoordinates : (Float, Float) -> Point2d
```

I have no idea if it works. I just thought of this now. It is more boilerplate, that's for sure.

**Comment by ianmackenzie** [comment]
I've also thought about an arrangement like that, but it seems weird for (e.g.) the `Point2d` module to have public functions that accept and return values of a private, non-exposed type...it seems like the sort of thing that might be outlawed in future versions of Elm. About the only way I can think of that would definitely work while maintaining encapsulation would be to have a single massive 'Implementations' module (which itself is exposed, but contains opaque types) and then modules that all just forward to it:

```elm
-- Implementations.elm
module Implementations
    exposing
        ( Point2d
        , Point3d
        , point2dFromCoordinates
        , point3dFromCoordinates
        )

type Point2d
    = Point2d ( Float, Float )

type Point3d
    = Point3d ( Float, Float, Float )

point2dFromCoordinates : ( Float, Float ) -> Point2d
point2dFromCoordinates =
    Point2d

point3dFromCoordinates : ( Float, Float, Float ) -> Point3d
point3dFromCoordinates =
    Point3d
```

```elm
-- Point2d.elm
module Point2d exposing (Point2d, fromCoordinates)

import Implementations

type alias Point2d =
    Implementations.Point2d

fromCoordinates : ( Float, Float ) -> Point2d
fromCoordinates =
    Implementations.point2dFromCoordinates
````

So end users *could* use types/functions from the `Implementations` module directly, but it would be easier and nicer to use the forwarding modules. I might end up using this sort of approach for future packages that implement polymorphic parametric curves and surfaces, but I think it's overkill for the core `opensolid/geometry` package.

**Comment by mpizenberg** [comment]
I'm not sure that it is considered as a private type since the `Public.Types` module is making some kind of a "symbolic" link with nothing more than an import (no type or type alias definition). It seems to be the kind of question worth an investigation with the community (I will ask a question on mailing list).

I'm not a big fan of this all in one Implementation structure.

**Comment by mpizenberg** [comment]
So I have tried to have few insights [in elm-discuss](https://groups.google.com/forum/#!topic/elm-discuss/-RqDm1vuwu4) and did not get many answers but few interresting points:

- Matthew Griffith used this form of public alias to private type in his [elm-style-animation library](http://package.elm-lang.org/packages/mdgriffith/elm-style-animation/latest) for his `State`s types. I think he is in the "high sphere" of elm community since he was [part of the presenters in last elm conference](https://www.youtube.com/watch?v=DsDwYqsLU3E). This might be an indication of not such a bad practice.
- Actually, we can make it so both the compiler and the documentation refer to the type as the public type. To do this, the code might have a form like:
```elm
-- Private.elm
module Private exposing (..)
type Test = SomeTest | OtherTest

-- Public.elm
module Public exposing (Test)
import Private
type alias Test = Private.Test

-- Test.elm
module Test exposing (testFunction)
import Public exposing (Test)
import Private
testFunction : Test
testFunction = Private.SomeTest
```

- At the other end of the spectrum (opposit to the "Implementation" approach), the concept of doing all your code in private modules and aliasing only the interface in a public module has been pushed to the extreme in the [elm-pivot library](https://github.com/yotamDvir/elm-pivot/blob/2.0.0/Pivot.elm) for exemple. Have a look at it when you have some time
