### ISSUE TITLE
Add Elliptical Arcs 

### ISSUE THREAD

**Issue by folkertdev** [opensolid/geometry#31]
My primary use case for elliptical arcs is working with svg paths.  

A full description of how svg uses and defines elliptical arcs is [part of the svg spec](https://www.w3.org/TR/SVG/implnote.html#ArcImplementationNotes).

The spec describes two parameterizations: 

**Both store**

* xAxisOffset (written as phi), the rotation offset relative to the x-axis
* the major and minor radii 

**endpoint** 

* stores two points (the start and end point) 
* the arc flag  (large or small arc)
* the sweep flag (direction of the arc - clockwise or counter-clockwise)

**center**

* stores one point (the center)
* stores two angles - the starting angle and the delta-theta

In svg path syntax, ellipses are described in the endpoint parameterization, and the endpoints are also 
used in correcting out of range radii. The rest of the math uses the center parameterization. 

<hr>
We discussed about constructors, here are some ideas in types. 

```elm
type EllipticalArc2d = ... 

-- constructor ideas 
with
    :  { centerPoint : Point2d, startPoint : Point2d, sweptAngle : Float, xAxisRotate Float, radii : (Float, Float) }
    -> Maybe EllipticalArc2d

fromAngles 
    :  { centerPoint : Point2d, startAngle : Float, sweptAngle : Float, xAxisRotate : Float, radii : (Float, Float) }
    -> EllipticalArc2d

fromEndpoints
    :  { startPoint : Point2d, endPoint : Point2d
   , radii : (Float, Float), xAxisRotate : Float, sweptAngle : SweptAngle }
    -> Maybe EllipticalArc2d

-- for conversion to svg 
endpointParameterizaton : 
    EllipticalArc2d
     -> { startPoint : Point2d, endPoint : Point2d, radii : (Float, Float), xAxisRotate : Float, sweptAngle : SweptAngle }
```
Because the radius cannot be deduced, the `with` constructor needs to return a maybe in case 
the radii and the xAxisRotate can't make an ellipse that goes through the point. 

The rest of the api would mirror `Arc2d`: properties, evaluation, transforms, arc length parameterization.

**Comment by ianmackenzie** [comment]
Should now be complete - just about to release!
