### ISSUE TITLE
Question: Frame2d -> Scale

### ISSUE THREAD

**Issue by acateland** [opensolid/geometry#44]
Hello,
First thanks for your libraries, they are neat.

I have a question Frame2d (and Frame3d) représent a coordinate system on wich you can project shape.
They can be translated and rotated, is it sane to think that they also could be scaled ?
For example to represent a scene in wich some element attached to a specific frame description could be automaticaly scaled down/rotated/translated  ?

**Comment by ianmackenzie** [comment]
Thanks @acateland! It's an excellent question, and one I've thought a lot about myself. It would certainly be *possible* to add some sort of 'scale' or 'units' field to `Frame2d` and `Frame3d`, and it would be convenient in several cases, but in general I'm worried that doing so would make those types more confusing and error-prone to use. Some things to consider:

  - What would happen if a negative or zero scale was specified for a frame? Already there's a fair bit of tricky logic inside `opensolid/geometry` to handle cases where `scaleAbout` functions are given a negative scaling factor, and having frames with scales would add more complexity.
  - If the common case is to have frames with a scale of 1 (and I think that *is* the common case), then I think it would be a bit too easy to write code that *assumed* a scale of 1 that would then break when encountering a frame with a different scale. For example, right now if you use something like [`Frame3d.toMat4`](http://package.elm-lang.org/packages/opensolid/linear-algebra-interop/2.0.0/OpenSolid-Interop-LinearAlgebra-Frame3d#toMat4) to convert a `Frame3d` to a `Mat4` transformation matrix, then you can assume the resulting matrix is orthonormal and you can invert it by just taking the transpose. But if you did that with a matrix that involved scaling, you'd get the wrong result!
  - I think of 'changing frames of reference' or 'moving' as a conceptually distinct operations from 'applying a scale factor', so I'd be a bit uncomfortable if operations like `placeIn` or `relativeTo` had the ability to potentially do both of those. I like the fact that right now you can be confident when reading code that a `placeIn` or `relativeTo` call is *only* performing a rigid body transformation, and `scaleAbout` *only* does scaling - makes it easier to figure out what sort of transformation is happening where.

In general, my preference so far has been to leave `Frame2d` and `Frame3d` without scale, and handle scale separately when necessary. For example, I'm currently working on a 3D scene graph framework based on this package, and it (internally) uses a [`Placement`](https://github.com/opensolid/scene/blob/master/src/OpenSolid/Scene/Placement.elm) type that encapsulates a `Frame3d` and a scale.

One thing I like about this approach is that I think it encourages good practices - the most common reason I can think of for a scaling factor on frames is for doing unit conversions (e.g. feet to meters), but doing a ton of unit conversions throughout an application is a recipe for disaster. It's much better to convert everything to SI units (meters etc.) as soon as possible, deal everywhere with meters, then possibly convert back to some other desired units just for output. If using this package means that applying scale factors is a bit annoying, then it gives you incentive to only do them when absolutely necessary, and I think that's probably a good thing.

Phew - sorry for the long reply! Would love to hear your thoughts =)

**Comment by acateland** [comment]
A long reply but full with info, i like the `Placement` solution, im working on a diagram designer where some element should be zoomable. More tought when i get back to this task.

Thanks a lot for your answer.

**Comment by ianmackenzie** [comment]
OK, I'll close this for now then - feel free to reopen later, I'm always happy to discuss these sorts of design questions!
